process.env.NODE_ENV = 'test';
const path = require('node:path');
const os = require('node:os');
process.env.DATABASE_PATH = path.join(os.tmpdir(), 'camila-cms-test.sqlite');
process.env.UPLOADS_DIR = path.join(os.tmpdir(), 'camila-cms-test-uploads');
const test = require('node:test');
const assert = require('node:assert/strict');
const request = require('supertest');
const sharp = require('sharp');
const { generateSecret, generate } = require('otplib');
const app = require('../server');
const { q } = require('../lib/db');
const { passwordRecord, encryptSecret, cookieOptions } = require('../lib/security');

let agent, csrf, secret;
async function signIn() { agent = request.agent(app); const token = await generate({ secret }); const response = await agent.post('/api/auth/login').send({ email: 'camila@example.test', password: 'a long test password', totp: token }).expect(200); csrf = response.body.csrfToken; return response; }
function protectedPost(path, body) { return agent.post(path).set('X-CSRF-Token', csrf).send(body); }

test.before(async () => { for (const table of ['audit_log','login_attempts','sessions','users','books','media_videos','news']) q('DELETE FROM ' + table).run(); secret = generateSecret(); q('INSERT INTO users(email,password_hash,totp_secret) VALUES(?,?,?)').run('camila@example.test', await passwordRecord('a long test password'), encryptSecret(secret)); });
test('admin endpoints reject anonymous access', async () => { await request(app).get('/api/admin/books').expect(401); await request(app).post('/api/admin/books').send({ title: 'x' }).expect(401); });
test('TOTP login accepts only valid password and current code', async () => { await request(app).post('/api/auth/login').send({ email: 'camila@example.test', password: 'wrong password', totp: '000000' }).expect(401); const response = await signIn(); assert.match(response.headers['set-cookie'][0], /HttpOnly/); assert.match(response.headers['set-cookie'][0], /SameSite=Strict/); });
test('production cookie configuration requires HTTPS', () => { assert.equal(cookieOptions(true).secure, true); assert.equal(cookieOptions(true).httpOnly, true); assert.equal(cookieOptions(true).sameSite, 'strict'); });
test('CSRF protects all state changes and logout clears the session', async () => { await agent.post('/api/admin/books').send({ title:'Blocked',year:2026,publisher:'Test' }).expect(403); await agent.post('/api/auth/logout').set('X-CSRF-Token', csrf).send({}).expect(204); await agent.get('/api/auth/me').expect(401); await signIn(); });
test('book CRUD, ordering, publication and public API work', async () => { const first = await protectedPost('/api/admin/books',{title:'<img src=x onerror=alert(1)>',year:2026,publisher:'Editorial',description_es:'Texto',description_en:'Text',published:1,featured_home:1,sort_order:1}).expect(201); const second = await protectedPost('/api/admin/books',{title:'Segundo libro',year:2025,publisher:'Editorial',published:0,sort_order:0}).expect(201); await agent.patch('/api/admin/books/'+second.body.id).set('X-CSRF-Token',csrf).send({published:1,featured_home:1}).expect(200); await protectedPost('/api/admin/books/reorder',{ids:[second.body.id,first.body.id]}).expect(204); const api = await request(app).get('/api/public/content').expect(200); assert.equal(api.body.version,1); assert.equal(api.body.books[0].title,'Segundo libro'); assert.equal(api.body.books[1].title,'<img src=x onerror=alert(1)>'); assert.equal(api.body.featured.books.length,2); await agent.delete('/api/admin/books/'+first.body.id).set('X-CSRF-Token',csrf).expect(204); });
test('news and Odisea CRUD validate inputs, publish, and place new videos first', async () => { const video = await protectedPost('/api/admin/videos',{youtube_id:'https://youtu.be/dQw4w9WgXcQ',title:'Una columna',published_at:'2026-10-02T12:00:00.000Z',published:1,sort_order:1}).expect(201); assert.equal(video.body.youtube_id,'dQw4w9WgXcQ'); const newest = await protectedPost('/api/admin/videos',{youtube_id:'https://youtu.be/9bZkp7q19f0',title:'La columna nueva',published_at:'2026-10-03T12:00:00.000Z',published:1}).expect(201); const publicContent = await request(app).get('/api/public/content').expect(200); assert.equal(publicContent.body.odisea[0].id,newest.body.id); const news = await protectedPost('/api/admin/news',{type:'award',title_es:'Premio',title_en:'Award',event_date:'2026-10-02',published:1,featured_home:1,sort_order:1}).expect(201); await agent.patch('/api/admin/news/'+news.body.id).set('X-CSRF-Token',csrf).send({title_es:'Premio actualizado'}).expect(200); await agent.delete('/api/admin/videos/'+video.body.id).set('X-CSRF-Token',csrf).expect(204); await agent.get('/api/admin/news/'+news.body.id).expect(200); });
test('SQL injection-shaped inputs and traversal image paths are rejected or inert', async () => { await protectedPost('/api/admin/books',{title:"x'); DROP TABLE books;--",year:2024,publisher:'Safe',cover_path:'../../data/camila.sqlite'}).expect(400); await request(app).post('/api/auth/login').send({email:"' OR 1=1 --",password:'x',totp:'000000'}).expect(401); const rows = await agent.get('/api/admin/books').expect(200); assert.ok(Array.isArray(rows.body)); });
test('upload blocks invalid formats and safely re-encodes a real image', async () => { await agent.post('/api/admin/upload').set('X-CSRF-Token',csrf).attach('image',Buffer.from('<svg onload=alert(1)>'),'bad.svg',{contentType:'image/svg+xml'}).expect(400); const png = await sharp({create:{width:2,height:2,channels:3,background:'#123456'}}).png().toBuffer(); const response = await agent.post('/api/admin/upload').set('X-CSRF-Token',csrf).attach('image',png,'cover.png',{contentType:'image/png'}).expect(201); assert.match(response.body.path,/^\/uploads\/[A-Za-z0-9_-]{20,}\.webp$/); });
test('security headers, non-indexing controls and private files protection are present', async () => { const admin = await request(app).get('/admin').expect(200); assert.match(admin.headers['content-security-policy'], /script-src 'self'/); assert.equal(admin.headers['x-robots-tag'],'noindex, nofollow, noarchive'); const content = await request(app).get('/api/public/content').expect(200); assert.equal(content.headers['x-content-type-options'],'nosniff'); assert.equal(content.headers['referrer-policy'],'strict-origin-when-cross-origin'); await request(app).get('/data/camila.sqlite').expect(404); await request(app).get('/node_modules/express/package.json').expect(404); await request(app).get('/uploads/../data/camila.sqlite').expect(404); });
test('expired sessions and rate limiting deny access', async () => { const me = await agent.get('/api/auth/me').expect(200); q('UPDATE sessions SET expires_at=? WHERE csrf_token=?').run('2000-01-01T00:00:00.000Z',me.body.csrfToken); await agent.get('/api/auth/me').expect(401); const separate = request(app); for(let i=0;i<5;i++) await separate.post('/api/auth/login').send({email:'nobody@example.test',password:'wrong',totp:'000000'}); await separate.post('/api/auth/login').send({email:'nobody@example.test',password:'wrong',totp:'000000'}).expect(429); });
